apiVersion: v1

kind: Service

metadata:
  name: nginx-svc-dev

spec:

  type: LoadBalancer

  selector:
    app: nginx-dev

  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: admin
      port: 81
      targetPort: 81