spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Category (PRODUCTS)         #카테고리 CUD 인증
            - id: category-route-protected
              uri: http://product-svc-prod.default.svc.cluster.local:8085
              predicates:
                - Path=/api/categories, /api/categories/**
                - Method=PUT, POST, DELETE
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: productServiceCB
                    fallbackUri: forward:/fallback/product
                - name: TokenAuthenticationFilter

            - id: category-route-public     #카테고리들 조회
              uri: http://product-svc-prod.default.svc.cluster.local:8085
              predicates:
                - Path=/api/categories, /api/categories/**
                - Method=GET
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: productServiceCB
                    fallbackUri: forward:/fallback/product

            # Product (PRODUCTS)
            - id: cart-route-protected
              uri: http://product-svc-prod.default.svc.cluster.local:8085
              predicates:
                - Path=/api/carts, /api/carts/**
                - Method=GET, POST, DELETE
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: productServiceCB
                    fallbackUri: forward:/fallback/product
                - name: TokenAuthenticationFilter

            - id: product-route-getAll-protected  # 상품 목록 조회 R 관리자용 인증
              uri: http://product-svc-prod.default.svc.cluster.local:8085
              predicates:
                - Path=/api/products
                - Method=GET
              order: 1
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: productServiceCB
                    fallbackUri: forward:/fallback/product

            - id: product-route-public          #상품 조회
              uri: http://product-svc-prod.default.svc.cluster.local:8085
              predicates:
                - Path=/api/products/**
                - Method=GET
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: productServiceCB
                    fallbackUri: forward:/fallback/product
              order: 2


            - id: product-route-protected     #상품 수정 및 삭제 인증
              uri: http://product-svc-prod.default.svc.cluster.local:8085
              predicates:
                - Path=/api/products, /api/products/**
                - Method=PATCH, PUT, POST, DELETE
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: productServiceCB
                    fallbackUri: forward:/fallback/product
                - name: TokenAuthenticationFilter

            - id: product-es-route-public   #상품 es 검색
              uri: http://product-svc-prod.default.svc.cluster.local:8085
              predicates:
                - Path=/api/search/**
                - Method=GET
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: productServiceCB
                    fallbackUri: forward:/fallback/product

            - id: product-images-route-protected   #이미지 업로드 인증
              uri: http://product-svc-prod.default.svc.cluster.local:8085
              predicates:
                - Path=/api/images/presigned-url, /api/images/presigned-url/**
                - Method=GET
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: productServiceCB
                    fallbackUri: forward:/fallback/product
                - name: TokenAuthenticationFilter
            # History
            - id: history-route
              uri: http://product-svc-prod.default.svc.cluster.local:8085
              predicates:
                - Path=/api/history, /api/history/**
                - Method=GET
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: productServiceCB
                    fallbackUri: forward:/fallback/product
                - name: TokenAuthenticationFilter
            # Order
            - id: order-route-pg
              uri: http://order-svc-prod.default.svc.cluster.local:8082
              predicates:
                - Path=/orders/**, /orders/payment/**, /api/orders/payment/**, /api/orders/payment
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: orderServiceCB
                    fallbackUri: forward:/fallback/order
              order: 1

            - id: order-route-protected
              uri: http://order-svc-prod.default.svc.cluster.local:8082
              predicates:
                - Path=/api/orders/**, /api/orders
                - Method=POST, GET, PATCH, DELETE
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: orderServiceCB
                    fallbackUri: forward:/fallback/order
                - name: TokenAuthenticationFilter
              order: 2

            # Payment
            - id: payment-route-public
              uri: http://payment-svc-prod.default.svc.cluster.local:8087
              predicates:
                - Path=/api/payments/toss/**
                - Method=GET
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: paymentServiceCB
                    fallbackUri: forward:/fallback/payment
              order: 1

            - id: payment-route-protected
              uri: http://payment-svc-prod.default.svc.cluster.local:8087
              predicates:
                - Path=/api/payments/**, /api/payments
                - Method=POST
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: paymentServiceCB
                    fallbackUri: forward:/fallback/payment
                - name: TokenAuthenticationFilter
              order: 2

            #  Deposit (PAYMENT)
            - id: deposit-route-protected
              uri: http://payment-svc-prod.default.svc.cluster.local:8087
              predicates:
                - Path=/api/deposits, /api/deposits/**    #deposit은 모두 인증
                - Method=POST, GET, PATCH, DELETE
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: paymentServiceCB
                    fallbackUri: forward:/fallback/payment
                - name: TokenAuthenticationFilter

            # User (AUTH)
            - id: user-route-public
              uri: http://auth-svc-prod.default.svc.cluster.local:8084
              predicates:
                - Path=/api/users
                - Method=GET
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: authServiceCB
                    fallbackUri: forward:/fallback/auth
              order: 1

            - id: user-route-protected
              uri: http://auth-svc-prod.default.svc.cluster.local:8084
              predicates:
                - Path=/api/users/**
                - Method=POST, GET, PATCH, DELETE
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: authServiceCB
                    fallbackUri: forward:/fallback/auth
                - name: TokenAuthenticationFilter
              order: 2

            # Auth
            - id: auth-route-login
              uri: http://auth-svc-prod.default.svc.cluster.local:8084
              predicates:
                - Path=/login/**, /oauth2/**
                - Method=GET
              order: 1

            - id: auth-route-public
              uri: http://auth-svc-prod.default.svc.cluster.local:8084
              predicates:
                - Path=/api/auth
                - Method=POST
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: authServiceCB
                    fallbackUri: forward:/fallback/auth
              order: 2

            - id: auth-route-protected
              uri: http://auth-svc-prod.default.svc.cluster.local:8084
              predicates:
                - Path=/api/auth/logout
                - Method=POST
              filters:
                - name: Retry
                  args:
                    retries: 10
                    statuses: [BAD_GATEWAY, SERVICE_UNAVAILABLE]
                - name: CircuitBreaker
                  args:
                    name: authServiceCB
                    fallbackUri: forward:/fallback/auth
                - name: TokenAuthenticationFilter
              order: 3


            # Swagger
            - id: user-api-docs
              uri: http://auth-svc-prod.default.svc.cluster.local:8084
              predicates:
                - Path=/v3/api-docs/auth
              filters:
                - RewritePath=/v3/api-docs/auth, /v3/api-docs

            - id: product-api-docs
              uri: http://product-svc-prod.default.svc.cluster.local:8085
              predicates:
                - Path=/v3/api-docs/products
              filters:
                - RewritePath=/v3/api-docs/products, /v3/api-docs

            - id: payment-api-docs
              uri: http://payment-svc-prod.default.svc.cluster.local:8087
              predicates:
                - Path=/v3/api-docs/payment
              filters:
                - RewritePath=/v3/api-docs/payment, /v3/api-docs

            - id: order-api-docs
              uri: http://order-svc-prod.default.svc.cluster.local:8082
              predicates:
                - Path=/v3/api-docs/order
              filters:
                - RewritePath=/v3/api-docs/order, /v3/api-docs

custom:
  jwt:
    secrets:
      app-key: ${JWT_SECRET}

logging:
  level:
    root: info

management:
  zipkin:
    tracing:
      endpoint: http://zipkin-svc-prod.default.svc.cluster.local:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /v3/api-docs/auth
      - name: product-service
        url: /v3/api-docs/products
      - name: order-service
        url: /v3/api-docs/order
      - name: payment-service
        url: /v3/api-docs/payment
resilience4j:
  circuitbreaker:
    configs:
      default:
        # DNS 해석 지연을 해결하기 위해, 최소 요청 횟수 설정을 사용할 것이므로 COUNT_BASED가 적절합니다.
        slidingWindowType: COUNT_BASED
        # 슬라이딩 윈도우 크기. 기본적으로 이 횟수만큼 요청이 들어와야 실패율을 계산합니다.
        slidingWindowSize: 100
        # 서킷이 열릴지 말지 결정하기 위해 필요한 최소 호출 횟수 (핵심 설정!)
        # 이 설정이 minimumNumberOfCalls입니다.
        # 예를 들어, 10개 미만의 요청은 실패하더라도 서킷 상태에 영향을 주지 않음.
        minimumNumberOfCalls: 10
        # 실패율 임계값. 이 비율을 초과하면 서킷이 열립니다. (기본 50.0%)
        failureRateThreshold: 50
        # 서킷이 열린(OPEN) 상태에서 부분적으로 열린(HALF_OPEN) 상태로 전환되기까지 대기하는 시간
        waitDurationInOpenState: 60s
        # 느린 호출(Slow Call)로 간주하는 시간 임계값
        slowCallDurationThreshold: 15s
        # 느린 호출 비율 임계값. 이 비율을 초과하면 서킷이 열립니다.
        slowCallRateThreshold: 100 # 초기 DNS 지연이 매우 길면 모든 요청이 느린 호출로 간주될 수 있으므로 일단 100으로 설정 (느린 호출로 인한 서킷 열림 방지)

    instances:
      # productServiceCB 인스턴스에 default 설정을 적용
      productServiceCB:
        baseConfig: default

      # orderServiceCB 인스턴스에 default 설정을 적용
      orderServiceCB:
        baseConfig: default

      # paymentServiceCB 인스턴스에 default 설정을 적용
      paymentServiceCB:
        baseConfig: default

      # authServiceCB 인스턴스에 default 설정을 적용
      authServiceCB:
        baseConfig: default
        # 최소 호출 횟수를 더 많이 늘립니다.
        minimumNumberOfCalls: 30
        # 초기 DNS 해석에 충분한 시간을 주기 위해, 타임아웃 설정을 관대하게 적용합니다.
        # 느린 호출로 간주하는 시간을 10초로 설정 (기본 5초)
        slowCallDurationThreshold: 15s
        # 서킷이 열린 상태에서 대기하는 시간을 1분 30초로 늘립니다.
        waitDurationInOpenState: 90s