apiVersion: apps/v1
kind: Deployment
#이 파일 정의
metadata:
  name: product-dpy-prod
#동작 정의
spec:
  replicas: 1
#  제어할 라벨
  selector:
    matchLabels:
      app: product-prod
#      pod 정의
  template:
    metadata:
      labels:
        app: product-prod
#        컨테이너 정의
    spec:
      containers:
        - name: product-pod-prod
          image: yuio7279/product
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: product-config-prod
            - secretRef:
                name: product-secret-prod
            - secretRef:
                name: secret-common-prod
      restartPolicy: Always
