apiVersion: v1
kind: Service
metadata:
  name: payment-svc-dev
spec:
  type: ClusterIP
  selector:
    app: payment-dev
  ports:
    - protocol: TCP
      port: 8087       # 내부 서비스 포트
      targetPort: 8087 # 컨테이너 포트
