name: CD-WORKFLOW

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

env:
  REGISTRY: docker.io
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  deploy:
    name: 쿠버네티스 배포
    runs-on: self-hosted

    steps:
      - name: 깃 브랜치 연결
        uses: actions/checkout@v5

      - name: 최신 Release 조회
        id: latest_release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput("tag", release.data.tag_name);

      - name: 이미지 교체
        run: |
          kubectl set image deployment.apps/${{ inputs.service-name }}-dpy-prod \
            ${{ inputs.service-name }}=${{ env.DOCKER_USER }}/${{ inputs.service-name }}:${{ steps.latest_release.outputs.tag}}

      - name: Secret 생성
        run: |
          if [[ "${{ inputs.service-name }}" == "auth" ]]; then
            echo "${{ secrets.SECRET_AUTH_PROD }}" | kubectl apply -f -
          fi
          
          if [[ "${{ inputs.service-name }}" == "product" ]]; then
            echo "${{ secrets.SECRET_PRODUCT_PROD }}" | kubectl apply -f -
          fi
          echo "${{ secrets.SECRET_COMMON_PROD }}" | kubectl apply -f -
          

      - name: 롤링 업데이트 진행
        run: |
          kubectl rollout status deployment.apps/${{ inputs.service-name }}-dpy-prod

      - name: 배포 상태 검증
        run: |
          kubectl get pods -l app=${{ inputs.service-name }}
#          rm -f secret-auth-prod.yaml || true
#          rm -f secret-product-prod.yaml || true
#          rm -f secret-common-prod.yaml || true
          
